extends:
  - stylelint-config-standard
  - stylelint-config-prettier
  - stylelint-config-idiomatic-order
rules:
  order/properties-alphabetical-order: null
  string-quotes: null
  selector-class-pattern: null
  no-descending-specificity: null
  selector-no-qualifying-type: null
  no-empty-source: null
  max-nesting-depth: 3
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
  declaration-no-important: true
  color-function-notation: null
  alpha-value-notation: null
  function-no-unknown: null
  import-notation: null
